"""Regenerates android/app/src/main/assets/borders/europe_countries.txt (issue #209).

Input: Natural Earth 1:50m admin-0 countries GeoJSON (public domain), e.g.
https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson

Usage: python tools/gen_country_borders.py <ne_50m_admin_0_countries.geojson> <out.txt> [tolerance_deg]

Keeps the European countries (minus Russia, whose footprint dwarfs the rest), clips away rings
that lie entirely outside the Europe bounding box (overseas territories), simplifies each ring
with Douglas-Peucker and rounds to 3 decimals (~100 m). Output: one ring per line,
"CC lon,lat lon,lat ...", evaluated with the even-odd rule per country (holes are just rings).
"""
import json
import sys


def in_bbox(p):
    return -25 <= p[0] <= 45 and 34 <= p[1] <= 72


def douglas_peucker(pts, tol):
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]
        bx, by = pts[b]
        dx, dy = bx - ax, by - ay
        length = (dx * dx + dy * dy) ** 0.5
        best, best_i = -1.0, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            if length > 0:
                dist = abs(dy * (px - ax) - dx * (py - ay)) / length
            else:
                dist = ((px - ax) ** 2 + (py - ay) ** 2) ** 0.5
            if dist > best:
                best, best_i = dist, i
        if best > tol:
            keep[best_i] = True
            stack.append((a, best_i))
            stack.append((best_i, b))
    return [p for p, k in zip(pts, keep) if k]


def main():
    src, dst = sys.argv[1], sys.argv[2]
    tol = float(sys.argv[3]) if len(sys.argv) > 3 else 0.002
    data = json.load(open(src, encoding="utf-8"))
    lines = [
        "# Simplified country boundaries for border-crossing detection (issue #209).",
        "# Source: Natural Earth 1:50m admin-0 countries (public domain), Europe subset.",
        "# Generated by tools/gen_country_borders.py (Douglas-Peucker %.4f deg, 3 decimals)." % tol,
        "# One ring per line: CC lon,lat lon,lat ... (even-odd rule per country).",
    ]
    points = 0
    for feature in data["features"]:
        props = feature["properties"]
        code = props.get("ISO_A2_EH")
        if props.get("CONTINENT") != "Europe" or code in ("RU", "-99", None):
            continue
        geom = feature["geometry"]
        polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
        for poly in polys:
            for ring in poly:
                if not any(in_bbox(q) for q in ring):
                    continue
                simplified = douglas_peucker([(round(x, 3), round(y, 3)) for x, y in ring], tol)
                deduped = []
                for q in simplified:
                    if not deduped or deduped[-1] != q:
                        deduped.append(q)
                if len(deduped) > 1 and deduped[0] == deduped[-1]:
                    deduped = deduped[:-1]
                if len(deduped) < 3:
                    continue
                points += len(deduped)
                lines.append(code + " " + " ".join("%g,%g" % q for q in deduped))
    with open(dst, "w", encoding="utf-8", newline="\n") as out:
        out.write("\n".join(lines) + "\n")
    print("rings=%d points=%d" % (len(lines) - 4, points))


if __name__ == "__main__":
    main()
